import type { Metadata } from 'next'
import { Geist } from 'next/font/google'
import './globals.css'
import { Toaster } from 'sonner'
import { ReactQueryProvider } from '@/components/molecules/ReactQueryProvider'
import { UserProvider } from '@/components/molecules/UserProvider'

const geistSans = Geist({
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.className} antialiased`}>
        <UserProvider>
          <ReactQueryProvider>
            <Toaster richColors />
            {children}
          </ReactQueryProvider>
        </UserProvider>
      </body>
    </html>
  )
}
